name: Backrooms
main: name.d3420b8b7fe04.def9a2a4.plugintemplate.BackroomsMainPlugin
bootstrapper: name.d3420b8b7fe04.def9a2a4.plugintemplate.BackroomsBootstrap
version: ${version}
api-version: "1.21"
author: You
description: A Paper plugin.

permissions:
  backrooms.admin:
    description: Allows access to all Backrooms commands
    default: op
  backrooms.reload:
    description: Allows reloading the config
    default: op
  backrooms.use:
    description: Allows entering and leaving the Backrooms
    default: true
  backrooms.admin:
    description: Allows admin backrooms commands (goto, event, spawn, despawn, enter, escalation, reset, list)
    default: op
  backrooms.regenerate:
    description: Allows regenerating backrooms worlds
    default: op
